// <auto-generated />
using System;
using Ato.Copilot.Core.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ato.Copilot.Core.Migrations
{
    [DbContext(typeof(AtoCopilotContext))]
    [Migration("20260225172118_Feature010_KnowledgeBase")]
    partial class Feature010_KnowledgeBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Ato.Copilot.Core.Models.Auth.CacSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SessionStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_CacSession_ExpiresAt");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_CacSession_UserId_Status");

                    b.ToTable("CacSessions");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Auth.CertificateRoleMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateSubject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateThumbprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MappedRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateSubject")
                        .IsUnique()
                        .HasDatabaseName("IX_CertMapping_Subject");

                    b.HasIndex("CertificateThumbprint")
                        .IsUnique()
                        .HasDatabaseName("IX_CertMapping_Thumbprint");

                    b.ToTable("CertificateRoleMappings");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Auth.JitRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("ActualDuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ApprovalDecisionAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApproverComments")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApproverDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApproverId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PimRequestId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceGroup")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeDisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketSystem")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VmName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("IX_JitRequest_RequestedAt");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_JitRequest_SessionId");

                    b.HasIndex("RoleName", "Scope")
                        .HasDatabaseName("IX_JitRequest_RoleName_Scope");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("IX_JitRequest_Status_ExpiresAt");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_JitRequest_UserId_Status");

                    b.ToTable("JitRequests");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.AlertIdCounter", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastSequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date");

                    b.ToTable("AlertIdCounters");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.AlertNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryError")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("IX_AlertNotification_SentAt");

                    b.HasIndex("AlertId", "Channel")
                        .HasDatabaseName("IX_AlertNotification_Alert_Channel");

                    b.ToTable("AlertNotifications");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlFamily")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientOverrides")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceGroupName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeverityOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerCondition")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .HasDatabaseName("IX_AlertRule_IsDefault");

                    b.HasIndex("SubscriptionId", "ControlFamily", "IsEnabled")
                        .HasDatabaseName("IX_AlertRule_Sub_Family_Enabled");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.AuditLogEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedControls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedResources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScanType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.AutoRemediationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlFamily")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceGroupName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("IX_AutoRemediationRule_Enabled");

                    b.HasIndex("SubscriptionId", "ControlFamily", "IsEnabled")
                        .HasDatabaseName("IX_AutoRemediationRule_Sub_Family_Enabled");

                    b.ToTable("AutoRemediationRules");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedResources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlertId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeDetails")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildAlertCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlFamily")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DismissalJustification")
                        .HasColumnType("TEXT");

                    b.Property<string>("DismissedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EscalatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupedAlertId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGrouped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendedAction")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("SlaDeadline")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlertId")
                        .IsUnique()
                        .HasDatabaseName("IX_ComplianceAlert_AlertId");

                    b.HasIndex("ControlFamily")
                        .HasDatabaseName("IX_ComplianceAlert_ControlFamily");

                    b.HasIndex("GroupedAlertId")
                        .HasDatabaseName("IX_ComplianceAlert_GroupedAlertId");

                    b.HasIndex("AssignedTo", "Status")
                        .HasDatabaseName("IX_ComplianceAlert_Assignee_Status");

                    b.HasIndex("SlaDeadline", "Status")
                        .HasDatabaseName("IX_ComplianceAlert_Sla_Status");

                    b.HasIndex("Status", "Severity")
                        .HasDatabaseName("IX_ComplianceAlert_Status_Severity");

                    b.HasIndex("SubscriptionId", "CreatedAt")
                        .HasDatabaseName("IX_ComplianceAlert_Sub_Created");

                    b.ToTable("ComplianceAlerts");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceAssessment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("AssessmentDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Baseline")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ComplianceScore")
                        .HasColumnType("REAL");

                    b.Property<string>("ControlFamilyResults")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutiveSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedControls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Framework")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NotAssessedControls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassedControls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgressMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceGroupFilter")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskProfile")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanPillarResults")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalControls")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssessedAt");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("SubscriptionId", "Framework");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssessmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolicyComplianceState")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "IsActive")
                        .HasDatabaseName("IX_ComplianceBaseline_Resource_Active");

                    b.HasIndex("SubscriptionId", "CapturedAt")
                        .HasDatabaseName("IX_ComplianceBaseline_Sub_Captured");

                    b.ToTable("ComplianceBaselines");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Framework")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceEvidence", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EvidenceCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("ControlId");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceFinding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoRemediable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlFamily")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefenderRecommendationId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyAssignmentId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyDefinitionId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemediatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemediatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemediationGuidance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemediationScript")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemediationTrackingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemediationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScanSource")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StigFinding")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StigId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("ControlFamily");

                    b.HasIndex("ControlId");

                    b.HasIndex("AssessmentId", "Severity");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveAlertCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ComplianceScore")
                        .HasColumnType("REAL");

                    b.Property<int>("CompliantResources")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlFamilyBreakdown")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("CriticalAlertCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedControls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HighAlertCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWeeklySnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NonCompliantResources")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassedControls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalControls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalResources")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsWeeklySnapshot", "CapturedAt")
                        .HasDatabaseName("IX_ComplianceSnapshot_Weekly_CapturedAt");

                    b.HasIndex("SubscriptionId", "CapturedAt")
                        .HasDatabaseName("IX_ComplianceSnapshot_Sub_CapturedAt");

                    b.ToTable("ComplianceSnapshots");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.EscalationPath", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EscalationDelayMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxEscalations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepeatIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TriggerSeverity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TriggerSeverity", "IsEnabled")
                        .HasDatabaseName("IX_EscalationPath_Severity_Enabled");

                    b.ToTable("EscalationPaths");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.MonitoringConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastEventCheckAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("NextRunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceGroupName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NextRunAt", "IsEnabled")
                        .HasDatabaseName("IX_MonitoringConfig_NextRun_Enabled");

                    b.HasIndex("SubscriptionId", "ResourceGroupName")
                        .IsUnique()
                        .HasDatabaseName("IX_MonitoringConfig_Sub_RG");

                    b.ToTable("MonitoringConfigurations");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.NistControl", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureImplementation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AzurePolicyDefinitionIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baselines")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Enhancements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("FedRampParameters")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpactLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnhancement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentControlId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Family");

                    b.HasIndex("ParentControlId");

                    b.ToTable("NistControls");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.RemediationPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("AutoRemediableCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DryRun")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailedStepId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalFindings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RemediationPlans");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.SuppressionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlFamily")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Justification")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("QuietHoursEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("QuietHoursStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceGroupName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "ExpiresAt")
                        .HasDatabaseName("IX_SuppressionRule_Active_Expires");

                    b.HasIndex("SubscriptionId", "ResourceId")
                        .HasDatabaseName("IX_SuppressionRule_Sub_Resource");

                    b.ToTable("SuppressionRules");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Kanban.RemediationBoard", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NextTaskNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("SubscriptionId", "IsArchived");

                    b.ToTable("RemediationBoards");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Kanban.RemediationTask", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedResources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlFamily")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FindingId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastOverdueNotifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedAlertId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemediationScript")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationCriteria")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("BoardId");

                    b.HasIndex("ControlId");

                    b.HasIndex("DueDate");

                    b.HasIndex("Status");

                    b.HasIndex("BoardId", "ControlFamily");

                    b.HasIndex("BoardId", "Status");

                    b.ToTable("RemediationTasks");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Kanban.TaskComment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemComment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mentions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentCommentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskId", "CreatedAt");

                    b.ToTable("TaskComments");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Kanban.TaskHistoryEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActingUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActingUserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskId", "Timestamp");

                    b.ToTable("TaskHistoryEntries");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Auth.JitRequestEntity", b =>
                {
                    b.HasOne("Ato.Copilot.Core.Models.Auth.CacSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.AlertNotification", b =>
                {
                    b.HasOne("Ato.Copilot.Core.Models.Compliance.ComplianceAlert", "Alert")
                        .WithMany("Notifications")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceAlert", b =>
                {
                    b.HasOne("Ato.Copilot.Core.Models.Compliance.ComplianceAlert", "GroupedAlert")
                        .WithMany("ChildAlerts")
                        .HasForeignKey("GroupedAlertId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GroupedAlert");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceAssessment", b =>
                {
                    b.OwnsOne("Ato.Copilot.Core.Models.Compliance.ScanSummary", "PolicyScanSummary", b1 =>
                        {
                            b1.Property<string>("ComplianceAssessmentId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("CompliancePercentage")
                                .HasColumnType("REAL")
                                .HasColumnName("PolicyScan_CompliancePercentage");

                            b1.Property<int>("Compliant")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PolicyScan_Compliant");

                            b1.Property<int>("NonCompliant")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PolicyScan_NonCompliant");

                            b1.Property<int>("PoliciesEvaluated")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PolicyScan_PoliciesEvaluated");

                            b1.Property<int>("ResourcesScanned")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PolicyScan_ResourcesScanned");

                            b1.HasKey("ComplianceAssessmentId");

                            b1.ToTable("Assessments");

                            b1.WithOwner()
                                .HasForeignKey("ComplianceAssessmentId");
                        });

                    b.OwnsOne("Ato.Copilot.Core.Models.Compliance.ScanSummary", "ResourceScanSummary", b1 =>
                        {
                            b1.Property<string>("ComplianceAssessmentId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("CompliancePercentage")
                                .HasColumnType("REAL")
                                .HasColumnName("ResourceScan_CompliancePercentage");

                            b1.Property<int>("Compliant")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ResourceScan_Compliant");

                            b1.Property<int>("NonCompliant")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ResourceScan_NonCompliant");

                            b1.Property<int>("PoliciesEvaluated")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ResourceScan_PoliciesEvaluated");

                            b1.Property<int>("ResourcesScanned")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ResourceScan_ResourcesScanned");

                            b1.HasKey("ComplianceAssessmentId");

                            b1.ToTable("Assessments");

                            b1.WithOwner()
                                .HasForeignKey("ComplianceAssessmentId");
                        });

                    b.Navigation("PolicyScanSummary");

                    b.Navigation("ResourceScanSummary");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceDocument", b =>
                {
                    b.OwnsOne("Ato.Copilot.Core.Models.Compliance.DocumentMetadata", "Metadata", b1 =>
                        {
                            b1.Property<string>("ComplianceDocumentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ApprovedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuthorizationBoundary")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DateRange")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PreparedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("SystemDescription")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ComplianceDocumentId");

                            b1.ToTable("Documents");

                            b1.WithOwner()
                                .HasForeignKey("ComplianceDocumentId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceFinding", b =>
                {
                    b.HasOne("Ato.Copilot.Core.Models.Compliance.ComplianceAssessment", null)
                        .WithMany("Findings")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ato.Copilot.Core.Models.Compliance.NistControl", null)
                        .WithMany()
                        .HasForeignKey("ControlId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.NistControl", b =>
                {
                    b.HasOne("Ato.Copilot.Core.Models.Compliance.NistControl", null)
                        .WithMany("ControlEnhancements")
                        .HasForeignKey("ParentControlId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.RemediationPlan", b =>
                {
                    b.OwnsMany("Ato.Copilot.Core.Models.Compliance.RemediationStep", "Steps", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AfterState")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("AutoRemediable")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("BeforeState")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ControlId")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Effort")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ExecutedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FindingId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Priority")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("RemediationPlanId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("RemediationType")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ResourceId")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<int>("RiskLevel")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Script")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Status")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("RemediationPlanId");

                            b1.ToTable("RemediationStep");

                            b1.WithOwner()
                                .HasForeignKey("RemediationPlanId");
                        });

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Kanban.RemediationBoard", b =>
                {
                    b.HasOne("Ato.Copilot.Core.Models.Compliance.ComplianceAssessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Kanban.RemediationTask", b =>
                {
                    b.HasOne("Ato.Copilot.Core.Models.Kanban.RemediationBoard", "Board")
                        .WithMany("Tasks")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Kanban.TaskComment", b =>
                {
                    b.HasOne("Ato.Copilot.Core.Models.Kanban.RemediationTask", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Kanban.TaskHistoryEntry", b =>
                {
                    b.HasOne("Ato.Copilot.Core.Models.Kanban.RemediationTask", "Task")
                        .WithMany("History")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceAlert", b =>
                {
                    b.Navigation("ChildAlerts");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceAssessment", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.NistControl", b =>
                {
                    b.Navigation("ControlEnhancements");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Kanban.RemediationBoard", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Kanban.RemediationTask", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
