// <auto-generated />
using System;
using Ato.Copilot.Core.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ato.Copilot.Core.Migrations
{
    [DbContext(typeof(AtoCopilotContext))]
    partial class AtoCopilotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.AuditLogEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedControls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedResources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScanType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceAssessment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Baseline")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ComplianceScore")
                        .HasColumnType("REAL");

                    b.Property<int>("FailedControls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Framework")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NotAssessedControls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassedControls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProgressMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalControls")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssessedAt");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("SubscriptionId", "Framework");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Framework")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceEvidence", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EvidenceCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("ControlId");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceFinding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoRemediable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlFamily")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefenderRecommendationId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyAssignmentId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyDefinitionId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemediationGuidance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemediationScript")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemediationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScanSource")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("ControlFamily");

                    b.HasIndex("ControlId");

                    b.HasIndex("AssessmentId", "Severity");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.NistControl", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureImplementation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AzurePolicyDefinitionIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baselines")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Enhancements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("FedRampParameters")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpactLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnhancement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentControlId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Family");

                    b.HasIndex("ParentControlId");

                    b.ToTable("NistControls");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.RemediationPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("AutoRemediableCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DryRun")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailedStepId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalFindings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RemediationPlans");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceAssessment", b =>
                {
                    b.OwnsOne("Ato.Copilot.Core.Models.Compliance.ScanSummary", "PolicyScanSummary", b1 =>
                        {
                            b1.Property<string>("ComplianceAssessmentId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("CompliancePercentage")
                                .HasColumnType("REAL")
                                .HasColumnName("PolicyScan_CompliancePercentage");

                            b1.Property<int>("Compliant")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PolicyScan_Compliant");

                            b1.Property<int>("NonCompliant")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PolicyScan_NonCompliant");

                            b1.Property<int>("PoliciesEvaluated")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PolicyScan_PoliciesEvaluated");

                            b1.Property<int>("ResourcesScanned")
                                .HasColumnType("INTEGER")
                                .HasColumnName("PolicyScan_ResourcesScanned");

                            b1.HasKey("ComplianceAssessmentId");

                            b1.ToTable("Assessments");

                            b1.WithOwner()
                                .HasForeignKey("ComplianceAssessmentId");
                        });

                    b.OwnsOne("Ato.Copilot.Core.Models.Compliance.ScanSummary", "ResourceScanSummary", b1 =>
                        {
                            b1.Property<string>("ComplianceAssessmentId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("CompliancePercentage")
                                .HasColumnType("REAL")
                                .HasColumnName("ResourceScan_CompliancePercentage");

                            b1.Property<int>("Compliant")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ResourceScan_Compliant");

                            b1.Property<int>("NonCompliant")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ResourceScan_NonCompliant");

                            b1.Property<int>("PoliciesEvaluated")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ResourceScan_PoliciesEvaluated");

                            b1.Property<int>("ResourcesScanned")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ResourceScan_ResourcesScanned");

                            b1.HasKey("ComplianceAssessmentId");

                            b1.ToTable("Assessments");

                            b1.WithOwner()
                                .HasForeignKey("ComplianceAssessmentId");
                        });

                    b.Navigation("PolicyScanSummary");

                    b.Navigation("ResourceScanSummary");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceDocument", b =>
                {
                    b.OwnsOne("Ato.Copilot.Core.Models.Compliance.DocumentMetadata", "Metadata", b1 =>
                        {
                            b1.Property<string>("ComplianceDocumentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ApprovedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("AuthorizationBoundary")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DateRange")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("PreparedBy")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("SystemDescription")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ComplianceDocumentId");

                            b1.ToTable("Documents");

                            b1.WithOwner()
                                .HasForeignKey("ComplianceDocumentId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceFinding", b =>
                {
                    b.HasOne("Ato.Copilot.Core.Models.Compliance.ComplianceAssessment", null)
                        .WithMany("Findings")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ato.Copilot.Core.Models.Compliance.NistControl", null)
                        .WithMany()
                        .HasForeignKey("ControlId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.NistControl", b =>
                {
                    b.HasOne("Ato.Copilot.Core.Models.Compliance.NistControl", null)
                        .WithMany("ControlEnhancements")
                        .HasForeignKey("ParentControlId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.RemediationPlan", b =>
                {
                    b.OwnsMany("Ato.Copilot.Core.Models.Compliance.RemediationStep", "Steps", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AfterState")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("AutoRemediable")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("BeforeState")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ControlId")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Effort")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ExecutedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FindingId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Priority")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("RemediationPlanId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("RemediationType")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ResourceId")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<int>("RiskLevel")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Script")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Status")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("RemediationPlanId");

                            b1.ToTable("RemediationStep");

                            b1.WithOwner()
                                .HasForeignKey("RemediationPlanId");
                        });

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.ComplianceAssessment", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("Ato.Copilot.Core.Models.Compliance.NistControl", b =>
                {
                    b.Navigation("ControlEnhancements");
                });
#pragma warning restore 612, 618
        }
    }
}
